# name: Deploy

# on:
#   workflow_run:
#     workflows: ["Build with Webpack"]
#     branches: ["main"]
#     types:
#       - completed

#   jobs:
#     setup:
#       uses: ./.github/workflows/ci.yml

#     build:
#       runs-on: ubuntu-latest

#       steps:
#         - name: Checkout
#           uses: actions/checkout@v3

#         - name: Deploy to S3
#           uses: shallwefootball/s3-upload-action@master
#           with:
#             aws_key_id: ${{ secrets.AWS_KEY_ID }}
#             aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
#             aws_bucket: ${{ secrets.AWS_BUCKET }}
#             source_dir: "dirname"

#         - name: Deploy to NPM
