name: Deploy

on:
  workflow_run:
    workflows: ["Build and Test"]
    branches: ["main"]
    types:
      - completed

jobs:
  deploy storybook to S3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: npm install
        run: |
          npm install

      - name: Build Storybook
        run: |
          npm run build-storybook

      - name: Info
        run: |
          pwd
          ls -l

      # - name: Deploy to S3
      #   uses: shallwefootball/s3-upload-action@master
      #   with:
      #     aws_key_id: ${{ secrets.AWS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      #     aws_bucket: ${{ secrets.AWS_BUCKET }}
      #     source_dir: "dirname"

  deploy to npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: npm install
        run: |
          npm install

      - name: Build Webpack
        run: |
          npx webpack --mode production

      - name: Info
        run: |
          pwd
          ls -l

      # - name: Deploy to S3
      #   uses: shallwefootball/s3-upload-action@master
      #   with:
      #     aws_key_id: ${{ secrets.AWS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      #     aws_bucket: ${{ secrets.AWS_BUCKET }}
      #     source_dir: "dirname"

      # - name: Deploy to NPM
