name: Build and Test

on:
  push:
    branches: ["main", "beta"]
  pull_request:
    branches: ["main", "beta"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint

      - name: Unit Tests
        run: |
          npm run test-coverage

      - name: Current Path and Files
        run: |
          pwd
          ls -l

      - name: Upload Test Coverage Results to Github
        uses: actions/upload-artifact@v4
        with:
          name: Test Coverage Results for Node ${{ matrix.node-version }}
          path: coverage

      - name: Build Webpack
        run: |
          npm run build

      - name: Build Storybook
        run: |
          npm run build-storybook
