name: Release

on:
  workflow_run:
    workflows: ["Deploy"]
    branches: ["main", "beta"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: npm clean install
        run: |
          npm clean-install

      - name: Build
        run: |
          npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
# References
# https://dev.to/kouts/automated-versioning-and-package-publishing-using-github-actions-and-semantic-release-1kce
# https://stackoverflow.com/questions/58311847/github-action-for-updating-package-json
