name: Release

on:
  workflow_run:
    workflows: ["Deploy"]
    branches: ["main"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: npm clean install
        run: |
          npm clean-install

      - name: Install semantic-release additional plugins
        run: npm install --save-dev @semantic-release/changelog @semantic-release/git

      - name: Build
        run: |
          npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
